import http from 'node:http';
import { query, literal } from './db.mjs';
import { issueToken, verifyPassword, verifyToken } from './auth.mjs';
const host=process.env.HOST||'127.0.0.1', port=Number(process.env.BACKEND_PORT);
const json=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(body));};
async function input(req){let raw='';for await(const chunk of req)raw+=chunk;return raw?JSON.parse(raw):{};}
const auth=(req)=>verifyToken(String(req.headers.authorization||'').replace(/^Bearer\s+/i,''));
const server=http.createServer(async(req,res)=>{try{
  if(req.method==='GET'&&req.url==='/api/health'){query('SELECT 1');return json(res,200,{status:'ready'});}
  if(req.method==='GET'&&req.url==='/api/auth/demo-credentials'){if(process.env.NODE_ENV==='production')return json(res,404,{error:'Not found'});const email=process.env.PROVISION_ADMIN_EMAIL||process.env.ADMIN_EMAIL||'',password=process.env.PROVISION_ADMIN_PASSWORD||process.env.ADMIN_PASSWORD||'';return email&&password?json(res,200,{email,password}):json(res,503,{error:'Demo credentials unavailable'});}
  if(req.method==='POST'&&req.url==='/api/auth/login'){const body=await input(req),email=String(body.email||'').trim().toLowerCase();const rows=query(`SELECT id,email,password_hash,name,role FROM runtime_users WHERE email=${literal(email)} LIMIT 1`);if(!rows[0]||!verifyPassword(String(body.password||''),rows[0][2]))return json(res,401,{error:'Invalid credentials'});const user={id:rows[0][0],email:rows[0][1],name:rows[0][3],role:rows[0][4]};return json(res,200,{token:issueToken(user),user});}
  if(req.method==='GET'&&req.url==='/api/auth/me'){const user=auth(req);if(!user)return json(res,401,{error:'Authentication required'});const rows=query(`SELECT id,email,name,role FROM runtime_users WHERE id=${Number(user.sub)}`);return rows[0]?json(res,200,{id:rows[0][0],email:rows[0][1],name:rows[0][2],role:rows[0][3]}):json(res,401,{error:'Account unavailable'});}
  if(req.method==='POST'&&req.url==='/api/runtime-ai/game-readiness'){const user=auth(req);if(!user)return json(res,401,{error:'Authentication required'});const body=await input(req),base=String(process.env.OPENROUTER_BASE_URL||'').replace(/\/$/,'');if(base!=='https://openrouter.ai/api/v1')return json(res,503,{error:'OpenRouter base URL is not canonical'});const prompt=String(body.prompt||'Recommend one concrete way to improve this Tetris session.');const provider=await fetch(`${base}/chat/completions`,{method:'POST',headers:{authorization:`Bearer ${process.env.OPENROUTER_API_KEY}`,'content-type':'application/json','x-title':'Blockline Tetris Runtime'},body:JSON.stringify({model:process.env.OPENROUTER_MODEL,max_tokens:220,messages:[{role:'system',content:'You are a concise Tetris strategy coach. Give one finding and one next action.'},{role:'user',content:prompt}]})});const data=await provider.json();if(!provider.ok||data.error)return json(res,502,{error:data.error?.message||`Provider status ${provider.status}`});const content=data.choices?.[0]?.message?.content;if(!data.id||!content)return json(res,502,{error:'Provider response lacked content or receipt'});const providerReceipt={id:data.id,model:data.model||process.env.OPENROUTER_MODEL,usage:data.usage||null};const saved=query(`INSERT INTO runtime_ai_results(user_id,feature,prompt,response,provider_id,model) VALUES(${Number(user.sub)},'game-readiness',${literal(JSON.stringify({prompt}))}::jsonb,${literal(JSON.stringify({content,providerReceipt}))}::jsonb,${literal(data.id)},${literal(providerReceipt.model)}) RETURNING id`);return json(res,200,{content,model:providerReceipt.model,providerReceipt,recordId:saved[0][0]});}
  return json(res,404,{error:'Not found'});
}catch(error){return json(res,500,{error:error.message});}});
server.listen(port,host,()=>console.log(`Tetris runtime API listening on http://${host}:${port}`));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(()=>process.exit(0)));
